### ISSUE TITLE
Rebble Grant: Complete rewrite for Pebble Parity

### ISSUE THREAD

**Issue by Willow-Systems** [pebble-dev/rebble-dev-portal#17]
This is the issue to track my grant to rebuild the (currently very limited) dev portal into a full self-service developer portal. 

I propose building a system wherein users can log in with their Rebble accounts and manage, upload, update, view and delete their watchfaces and applications without interaction from anyone else. It will aim for feature parity with the original pebble developer portal. 

Here's the big ol' to-do list:

## Basics
- [ ] A new frontend that can be served on existing Rebble infrastructure
- [ ] Integration with auth.rebble.io to authenticate users
- [ ] Display user's existing applications
- [ ] Accept the required information to submit a new app
- [ ] Write an api endpoint that accepts, validates and creates a new application

### Submit API
- [ ] Create an API that allows the uploading of pbw, assets and data for new applications or faces
- [ ] Gracefully handle missing fields
- [ ] Validate appinfo.json 
- [ ] Validate user identity
- [ ] Gracefully handle invalid or malicious submissions
- [ ] Carry out any other required validation of fields (i.e. image file types)
- [ ] Build in line with the existing python/flask APIs
- [ ] Ensure API is idempotent such that duplicate entries for the same application are not possible

### New release API
- [ ] Allow uploading of new .pbw and new release notes to update apps
- [ ] Validate user has permissions to update apps
- [ ] Gracefully handle errors
- [ ] Allow uploading of new screenshots etc

### Edit API
- [ ] Facilitate developers changing fields after creation (title, description etc)
- [ ] Facilitate the creation and deletion of screenshots after upload
- [ ] Allow users to toggle app visibility (if required)
- [ ] Enforce any required limitations (e.g. field lengths)
- [ ] Gracefully handle errors

### Deletion API
- [ ] Allow users to delete apps
- [ ] Cleanly and safely clear up database entries

### Developer Update API
- [ ] Allow users to update their developer name

### Front end
- [ ] Create a front end that displays the user's existing applications
- [ ] Have a clear process for uploading new apps, that makes it easy for first time users
- [ ] Provide a simple method for updating app fields after creation
- [ ] Display pertinent data about developer's apps to them (app name, supported platforms etc)
- [ ] Display the user's developer profile and allow them to edit their name
- [ ] Support users on Linux, Mac and Windows, Chrome and Firefox (Desktop only)
- [ ] Display a first time screen to new developers without any apps
- [ ] Display any errors clearly, such that validation issues can be corrected
- [ ] Provide a method to delete and update screenshots
- [ ] Provide a method to publish new app releases

### Misc
- Ensure there are protections in place to defend against attacks to Rebble infrastructure
- Ensure submissions are valid so that errors caused by user input are caught before attempting to write to db
- Ensure there is no avenue to damaging existing data
- Ensure expected security is in place (users cannot affect apps they don't own etc)
- Ensure API design is sensible, and matches the style of the existing RWS infrastructure

# Milestones
These are the following proposed milestones:

1 - Upload only -> Allow users to upload new apps to the appstore, and view their existing apps    

2 - Claim developer IDs -> Build a system to allow developers who's rebble accounts are not linked to their developer IDs to link the two. This will require rebble admin interaction 

3 - Edit and Delete -> Allow users to edit the fields of their existing apps, and delete them

**Comment by Willow-Systems** [comment]
@jwise I have reordered the to-do list so it's in line with the milestones now.

**Comment by Willow-Systems** [comment]
Friendly poke @jwise @ishotjr

**Comment by ishotjr** [comment]
@Willow-Systems all of my Rebble time this month went to accounting/tax stuff, but my goal is to dive back into grants stuff this weekend! 💖

**Comment by Willow-Systems** [comment]
> all of my Rebble time this month went to accounting/tax stuff
Ah, the _fun_ stuff!

> but my goal is to dive back into grants stuff this weekend!
:tada:
